# Kathara base image with additional pip packages
# ---- List ----
# - requests
# - numpy
FROM kathara/base:latest

RUN apt update &&\
    apt install -y python3.11-venv &&\
    python3 -m venv venv &&\
    . venv/bin/activate &&\
    pip3 install requests numpy