version: '3.8'
services:
  r1:
    build:
      context: .
      dockerfile: Dockerfile.Quagga
    privileged: true
    hostname: r1
    volumes:
      - ./config:/etc/quagga
    command: bash -c "
      /etc/init.d/quagga
      && /etc/init.d/zebra start
      && /etc/init.d/ospfd start
      && tail -f /dev/null"
  pc1:
    build:
      context: .
      dockerfile: Dockerfile.PC
    privileged: true
    hostname: pc1
    command: bash -c "
      ip addr flush dev eth0
      && ip addr add 10.0.1.254/24 dev eth0
      && tail -f /dev/null"