version: '3.8'
services:
  r1:
    build:
      context: ../..
      dockerfile: Dockerfile
    privileged: true
    hostname: r1
    volumes:
      - ../../config/global:/etc/quagga
      - ../../config/topology1/R1.sh:/R1.sh
    command: bash -c "
      /etc/init.d/quagga
      && /etc/init.d/zebra start
      && /etc/init.d/ospfd start
      && ./R1.sh
      && tail -f /dev/null"
  r2:
    build:
      context: ../..
      dockerfile: Dockerfile
    privileged: true
    hostname: r2
    volumes:
      - ../../config/global:/etc/quagga
      - ../../config/topology1/R2.sh:/R2.sh
    command: bash -c "
      /etc/init.d/quagga
      && /etc/init.d/zebra start
      && /etc/init.d/ospfd start
      && ./R2.sh
      && tail -f /dev/null"
  r3:
    build:
      context: ../..
      dockerfile: Dockerfile
    privileged: true
    hostname: r3
    volumes:
      - ../../config/global:/etc/quagga
      - ../../config/topology1/R3.sh:/R3.sh
    command: bash -c "
      /etc/init.d/quagga
      && /etc/init.d/zebra start
      && /etc/init.d/ospfd start
      && ./R3.sh
      && tail -f /dev/null"
  r4:
    build:
      context: ../..
      dockerfile: Dockerfile
    privileged: true
    hostname: r4
    volumes:
      - ../../config/global:/etc/quagga
      - ../../config/topology1/R4.sh:/R4.sh
    command: bash -c "
      /etc/init.d/quagga
      && /etc/init.d/zebra start
      && /etc/init.d/ospfd start
      && ./R4.sh
      && tail -f /dev/null"
  r5:
    build:
      context: ../..
      dockerfile: Dockerfile
    privileged: true
    hostname: r5
    volumes:
      - ../../config/global:/etc/quagga
      - ../../config/topology1/R5.sh:/R5.sh
    command: bash -c "
      /etc/init.d/quagga
      && /etc/init.d/zebra start
      && /etc/init.d/ospfd start
      && ./R5.sh
      && tail -f /dev/null"
  pc1:
    build:
      context: ../..
      dockerfile: Dockerfile
    privileged: true
    hostname: pc1
    volumes:
      - ../../config/global:/etc/quagga
      - ../../config/topology1/PC1.sh:/PC1.sh
    command: bash -c "
      /etc/init.d/quagga
      && /etc/init.d/zebra start
      && ./PC1.sh
      && tail -f /dev/null"
  pc2:
    build:
      context: ../..
      dockerfile: Dockerfile
    privileged: true
    hostname: r2
    volumes:
      - ../../config/global:/etc/quagga
      - ../../config/topology1/PC2.sh:/PC2.sh
    command: bash -c "
      /etc/init.d/quagga
      && /etc/init.d/zebra start
      && ./PC2.sh
      && tail -f /dev/null"